steps:
  - label: "CUDA - Julia 1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
    command: |
      julia -e 'using Pkg

                println("--- :julia: Instantiating environment")
                Pkg.develop(path=".")

                println("+++ :julia: Running tests")
                Pkg.test("TrixiCUDA")'
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60
    if: build.message !~ /\[skip tests\]/
