name: Documentation

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request:

jobs:
  build:
    name: Build & Deploy Docs
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Julia 1.10
        uses: julia-actions/setup-julia@v2
        with:
          version: "1.10"

      - name: Restore Julia cache
        uses: julia-actions/cache@v2

      - name: Instantiate docs environment
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Build & deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      # for Documenter via GitHub Actions
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}  # optional: SSH deploy key
        run: julia --project=docs/ --color=yes docs/make.jl